### ISSUE TITLE
structure of SEO

### ISSUE THREAD

**Issue by zorg-iris** [leogout/SeoBundle#10]
Hi would it be possible to consider adding your structure to hand this variable  : 
   ```
http-equiv:
        'Content-Type':         text/html; charset=utf-8
        'X-Ua-Compatible':      IE=EmulateIE7
charset:
        UTF-8:    ''
head:
        "dir" : ltr
        'xmlns':              http://www.w3.org/1999/xhtml
        'xmlns:og':           http://opengraphprotocol.org/schema/
```
and maybe to get separatly "attributes" ?
```
<html  {{ leogout_seo_html_attributes()  }}>
       <head {{ leogout_seo_head_attributes() }} >
            {{ leogout_seo() }}
       </head>
</html>
```
Tank for your help

**Comment by pszalko** [comment]
As a user of this bundle I would prefer to stick only to SEO meta tags and not mix all other meta tags and attributes.

It will be easier to maintain your code when this library is focused only on SEO.

**Comment by leogout** [comment]
Hello, thank you both for your input and suggestions. I agree with @pszalko, also I don't use Symfony anymore so I won't be able to upate anything this critical without risking a headache... I'll close this one.
