### ISSUE TITLE
Generates "name" instead of "property"

### ISSUE THREAD

**Issue by revollat** [leogout/SeoBundle#16]
The Facebook sharing debugger tool (https://developers.facebook.com/tools/debug/sharing/) gives me a warning about using "name" instead of "property" inside the générated metas, e.g. :

`<meta name="og:image" content="..." />` should be `<meta property="og:image" content="..." />` according to FB best practices on og tags. 

Is there a way to modify this behaviour without modifying the bundle source code directly ?

**Comment by tugrul** [comment]
I created a pull request for this. Please merge & deploy it.

**Comment by leogout** [comment]
Thanks for pointing this out.
