### ISSUE TITLE
Warning on sf 5.2 - Seo generator services must be public.

### ISSUE THREAD

**Issue by ucay** [leogout/SeoBundle#22]
Trying this bundle for my Symfony v5.2 (skeleton, not the web-skeleton) got an error

` Seo generator services must be public, but "leogout_seo.generator.basic" is not.`

it's happen for all generator (basic, og and twitter)

try setting for default, not working
```
services:
    _defaults:
        public: true
```

but, add `public="true"` in the service (seo/basic.xml) can solve the problem, but have no time  try to the other major version of symfony.

**Comment by leogout** [comment]
Hello, I would be happy to accept a PR for this if anyone has time. I haven't used Symfony in years so it wouldn't be wise for me to code this....

**Comment by leogout** [comment]
I would l'île yo create a realease for this. Is it a breaking change ? Or is the property "public" supported in older versions of symfony ?

**Comment by sarim** [comment]
In previous versions it was default for services to be public. So if you omitted the tag, it was public. This behavior was changed in 3.4.
https://symfony.com/blog/new-in-symfony-3-4-services-are-private-by-default

**Comment by EdwinLove** [comment]
Would be really nice if this was released. Can't use the bundle as it is. Older versions (and they would be pretty old being pre 3.4) would not break with the addition of public = true

**Comment by sarim** [comment]
I'm using it with "dev-master" as version in composer.json

**Comment by leogout** [comment]
Thanks for the reminder, check out the v1.2.5

**Comment by EdwinLove** [comment]
Great, many thanks, didn't expect such a quick response!
