### ISSUE TITLE
Github Action failing to build project

### ISSUE THREAD

**Issue by leogout** [leogout/SeoBundle#26]
https://github.com/leogout/SeoBundle/actions/runs/2846891571

There seems to be a problem with the action config, I am no expert but I'll try to fix this ASAP.

**Comment by tugrul** [comment]
@leogout I fixed configuration file but it encountered a permission issue now.

> denied: installation not allowed to Create organization package

I think some configurations should make on settings. https://docs.github.com/en/packages/learn-github-packages/about-permissions-for-github-packages

**Comment by tugrul** [comment]
@leogout  It looks solved.

**Comment by leogout** [comment]
Thanks @tugrul , that seems to have worked : 
![image](https://user-images.githubusercontent.com/9843962/184373236-1a1cdccd-2348-4727-9973-3514996e21c2.png)
