### ISSUE TITLE
Add to basicTag

### ISSUE THREAD

**Issue by xorgxx** [leogout/SeoBundle#30]
Hi i m'y looking to add MetaTag dynamique how i can do this ?

**Comment by leogout** [comment]
https://github.com/leogout/SeoBundle#setting-values-dynamically

**Comment by xorgxx** [comment]
sorry my question was not clair. what i want to doo it's to add metaTag (hreflang, ....) dynamique ?

**Comment by twin-elements** [comment]
@xorgxx Did you find a solution?

**Comment by xorgxx** [comment]
@twin-elements Well y have to make one for my need [NeoxSeoBundle](https://github.com/xorgxx/NeoxSeoBundle).
Regard

**Comment by leogout** [comment]
I'm sorry I never came back to see your answer... Sorry that you had to create your own bundle, this one supports what you needed. It is in the readme, at the end : https://github.com/leogout/SeoBundle?tab=readme-ov-file#advanced-usage

**Comment by twin-elements** [comment]
@leogout  Hi :)

The hreflang link must look like this:
```
<link rel="alternate" hreflang="pl" href="https://site.com/page-pl">
<link rel="alternate" hreflang="en" href="https://site.com/page-en">
<link rel="alternate" hreflang="x-default" href="https://site.com/page-en">
```

In TagBuilder we have

```
    public function addLink(string $name, ?string $href = null, ?string $rel = null, ?string $type = null,
                            ?string $title = null) : LinkTag
    {
        return $this->links[$name] = $this->tagFactory
            ->createLink()
            ->setHref($href)
            ->setRel($rel)
            ->setType($type)
            ->setTitle($title);
    }
```

It is not possible to add a custom attribute (hreflang).

**Comment by leogout** [comment]
Ooh right, now I get it, thanks for explaining. Quite frankly I created this bundle 8 years ago, I hadn't even graduated from my CS degree. This bundle is waaay overengeneered for generating meta tags and it's been a pebble in my shoe for a long time now. I think I'll mark it as unmaintained for now on. Thanks for using it though !
