### ISSUE TITLE
You have requested a non-existent service "leogout_seo.provider.generator".

### ISSUE THREAD

**Issue by nicodemuz** [leogout/SeoBundle#6]
The following code:
```
$this->get('leogout_seo.provider.generator')->get('basic')->fromResource($listing);
```

Gives me the following error:
```
You have requested a non-existent service "leogout_seo.provider.generator".
```

Is the documentation outdated?

**Comment by nicodemuz** [comment]
```
$this->get('leogout_seo.generator.basic')->fromResource($listing);
```

This seems to get rid of the error but it still doesn't show the correct meta tags. Still shows the defaults as defined in config.yml.

**Comment by nicodemuz** [comment]
Updating to `dev-master` seems to solve my issue.

@leogout Recommend to issue a new release.

**Comment by leogout** [comment]
Hi, thanks for opening this issue, the latest release have been updated to 1.1.0.
