### ISSUE TITLE
Upgrade to Symfony 4

### ISSUE THREAD

**Issue by gander** [leogout/SeoBundle#7]
It's time to update package requirements -> Symfony 4.0

**Comment by alyamovsky** [comment]
agreed

**Comment by leogout** [comment]
Hi guys, long time no see!
Sorry I was quite busy these days. I've updated the dependencies requirements, tell me if you spot any problem. I'll test it this afternoon and close this issue if it works for me. Feel free to reopen it if anything bad happens.

Cheers.

**Comment by leogout** [comment]
Ok I've tested it and I've added it to the `symfony/recipes-contrib` as well.
If you allow composer to do it, the config file for the library will be automatically created in config/packages/leogout_seo.yaml with default values.
